# Generated by Django 5.2.2 on 2025-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_hotel_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
