# Generated by Django 5.1.6 on 2025-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_tone',
            field=models.CharField(choices=[('appetizing', 'Appetizing'), ('formal', 'Formal'), ('casual', 'Casual'), ('humorous', 'Humorous'), ('poetic', 'Poetic')], default='appetizing', help_text='Tone style for AI-generated description', max_length=20),
        ),
    ]
