# Generated by Django 5.2.2 on 2025-08-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_tag_menuitem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('table_code', models.SlugField(blank=True, max_length=40, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/tables/')),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='menu.hotel')),
            ],
            options={
                'ordering': ['hotel_id', 'number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.diningtable'),
        ),
        migrations.AddConstraint(
            model_name='diningtable',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='unique_table_per_hotel'),
        ),
    ]
