# Generated by Django 5.2 on 2025-08-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_diningtable_order_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
